INSERT INTO USER (ID,EMAIL,NAME,PASSWORD,USER_ID) VALUES (1,'byunw@bc.edu','우석','1111','alex1461');
INSERT INTO USER (ID,EMAIL,NAME,PASSWORD,USER_ID) VALUES (2,'david@bc.edu','형석','2222','david1461');
